# Generated by Django 5.2.8 on 2025-11-17 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitalApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'super_admin'}, on_delete=django.db.models.deletion.PROTECT, related_name='hospitals_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
