# Generated by Django 5.2.8 on 2025-11-17 12:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitalApp', '0001_initial'),
        ('userApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.URLField(blank=True, null=True)),
                ('specialization', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('chamber_room', models.CharField(blank=True, max_length=50, null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospitalApp.hospital')),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profiles',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration', models.IntegerField(help_text='Duration in minutes for each appointment slot (e.g., 15).')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(help_text='User (Hospital Admin or Staff) who created the schedule.', limit_choices_to=models.Q(('role', 'hospital_admin'), ('role', 'staff'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='schedules_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctorApp.doctorprofile')),
            ],
            options={
                'ordering': ['available_date', 'start_time'],
                'unique_together': {('doctor', 'available_date', 'start_time')},
            },
        ),
    ]
