# Generated by Django 5.2.8 on 2025-11-17 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['days', 'available_date', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='days',
            field=models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesDay', 'WednesDay'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='saturday', help_text='Day of the week.', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'days', 'available_date', 'start_time')},
        ),
        migrations.CreateModel(
            name='DoctorQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Qualification Title.', max_length=150, unique=True)),
                ('institution', models.CharField(help_text='Institution Name.', max_length=150)),
                ('passing_year', models.PositiveIntegerField(help_text='Year of Passing.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='doctorApp.doctorprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSpecialized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Specilized in.', max_length=150, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specilazed', to='doctorApp.doctorprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
