# Generated by Django 5.2.8 on 2025-11-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0002_alter_doctorschedule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorspecialized',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialized',
            field=models.ManyToManyField(related_name='doctors', to='doctorApp.doctorspecialized'),
        ),
    ]
