# Generated by Django 5.2.8 on 2026-08-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0003_remove_doctorspecialized_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorqualification',
            name='name',
            field=models.CharField(help_text='Qualification Title.', max_length=150),
        ),
    ]
