# Generated by Django 5.2.8 on 2026-08-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0004_alter_doctorqualification_name'),
        ('hospitalApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='hospital',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital',
            field=models.ManyToManyField(help_text='One doctor can belongs to multiple hospitals.', related_name='doctors', to='hospitalApp.hospital'),
        ),
    ]
