# Generated by Django 5.2.8 on 2026-08-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0006_doctorreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['days', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'days', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='available_date',
        ),
    ]
