# Generated by Django 5.2.8 on 2025-11-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['day', 'appointment_date', 'appointment_time']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.CharField(blank=True, choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesDay', 'WednesDay'), ('thursday', 'Thursday'), ('friday', 'Friday')], help_text='Day of the week.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='schedule_time',
            field=models.CharField(blank=True, help_text='Time Slot.', max_length=100, null=True),
        ),
    ]
