# Generated by Django 5.2.8 on 2026-01-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentApp', '0003_alter_appointment_options_appointment_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'appointment_time']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='day',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='schedule_time',
        ),
    ]
