# Generated by Django 5.2.8 on 2026-08-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0002_initial'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hospital',
        ),
        migrations.AddField(
            model_name='customuser',
            name='hospital',
            field=models.ManyToManyField(help_text='Hospital this user is associated with (Null for Super Admin/Patient).', related_name='users', to='hospitalApp.hospital'),
        ),
    ]
